[package]
name = "contract"
version = "0.1.0"
authors = ["Hello The Dream"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
unc-sdk = "2.0.3"
unc-contract-standards = "2.0.3"
unc-sys = "2.0.3"
