[package]
name = "w_unc"
version = "1.0.0"
authors = ["Utility Inc <hello@utnet.org>", "Jongun <jongun@gmail.com>"]
license = "GPL-2.0-or-later"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
unc-sdk = "2.2.1"
unc-contract-standards = "2.2.1"

[dev-dependencies]
