[package]
name = "whitelist"
version = "0.2.0"
authors = ["Utility Inc <hello@utnet.org>"]
license = "GPL-2.0-or-later"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
borsh = "1.3"
unc-sdk = { version = "2.0.6", features = ["unit-testing", "unstable"] }
