[package]
name = "multisig-factory"
version = "0.1.0"
authors = ["Utility Inc <hello@utnet.org>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
unc-sdk = "2.0.6"

[dev-dependencies]
borsh = { version = "1.3"}
