[package]
name = "airdrop"
version = "0.1.0"
authors = ["Hello Inc <hello@utnet.org>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
borsh = "1.3"
unc-sdk = { version = "2.0.3"}
