[package]
name = "airdrop"
version = "0.1.0"
authors = ["Utiility Inc <hello@utnet.org>"]
edition = "2021"
license = "GPL-2.0-or-later"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
unc-sdk = { version = "2.3.0", features = ["unit-testing", "unstable"] }
