[package]
name = "lockup-factory"
version = "0.2.1"
authors = ["Angelblock <angelblock@starduststaking.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
unc-sdk = "2.0.6"
hex = "0.4"

[dev-dependencies]
borsh = { version = "1.3"}
