[package]
name = "token-receiver"
version = "0.0.1"
authors = ["Utility Inc <hello@utnet.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
unc-sdk = { version = "2.3.2" }
unc-contract-standards = { version = "2.3.2" }
