[package]
name = "non-fungible-token"
version = "0.1.0"
authors = ["Utility Inc <hello@utnet.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
unc-sdk = { version = "2.3.2", features = ["unit-testing"] }
unc-contract-standards = { version = "2.3.2" }
