name: Test
on:
  workflow_call:

jobs:
  code-formatting:
    name: Code Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: cargo fmt --check

  code-linter:
    name: Code Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run cargo clippy
        run: |
          rustup component add clippy
          cargo clippy --all-features --workspace --tests -- --warn clippy::all --warn clippy::nursery

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: check artifacts
        run: | 
          rustup target add wasm32-unknown-unknown
          build_all_docker.sh --check

      - name: Run cargo test
        run: cargo test

      - name: check artifacts
        run: | 
          rustup target add wasm32-unknown-unknown
          test_all.sh
